### ISSUE TITLE
DashBoard values do not update from changes through Stats activity

### ISSUE THREAD

**Issue by scensorECHO** [FitFast/FitFast-Android#10]
After updating the ‘STATS’ page with weight and goal weight, the ‘BMI’, ‘Lbs Lost’, ‘Lbs left’, ‘Maitnence Cals’, ‘Daily cals’, ‘Target diff’ values do not update correctly. They stay at what they were before

Potential Fix: Implement SharedPreferences in order to push/pull data from that map between activities where necessary, see above comment at top of page 2 and [http://techblogon.com/android-sharedpreferences-example-code/]

**Comment by ryan-peirce** [comment]
These are hard coded place holders until we fully integrate all classes. Re-open if it's still an issue after that point.
