### ISSUE TITLE
Large calorie value under Start Workout breaks DashBoard layout

### ISSUE THREAD

**Issue by scensorECHO** [FitFast/FitFast-Android#11]
After inputting a large caloric value under ‘Start Workout’, Entering it, and going Back to DashBoard, the formatting gets messed up. This also happens after inputting a large caloric value under ‘Enter Food’.

Potential Fix: Switch to a horizontal LinearLayout for each row and implement a better weighting to allow correct spacing for the label text and calories (3:2, 2:1, or 3:1, test it out). Also limitation of user input on workout calories, there should be no >5 digits values in a daily workout.

**Comment by NabaShauk** [comment]
User cannot enter a value >5 digits anymore. That part of this issue is fixed. Similar to issue #9 so its being closed.
