### ISSUE TITLE
No Username Textfield/option

### ISSUE THREAD

**Issue by EddyLopez** [FitFast/FitFast-Android#36]
- Currently, the Create Account page has you sign up with your Full Name and Password. Never does it ask you to create a username. The main page (Log in page) asks you for a 'Username'.

**Comment by ryan-peirce** [comment]
Changed to "User". For the scope of this project we can just use user. Since we are storing it locally, it's assumed that the phone's owner would know all users by name. Re-open if anyone disagrees.
