### ISSUE TITLE
Incomplete information on the create account page, still allows you to create an account.

### ISSUE THREAD

**Issue by EddyLopez** [FitFast/FitFast-Android#37]
- When creating an account, you can leave anything blank (Weight, Height, Gender, Name, Age, BMI, etc.) and the account will still be created.

Make sure all fields are properly filled before proceeding.

**Comment by EddyLopez** [comment]
To add to this, leaving either 'Activity Level' and/or 'Time Frame' empty will still allow you to create an account.

**Comment by scensorECHO** [comment]
This might not be an issue altogether. Some information can be left empty, but will leave the account limited. Without information for a workout plan, the app won't give suggestions for daily calories and more. We should be more clear in the account creation activity about which fields are required to create an account
