### ISSUE TITLE
Password Issues when Creating an Account (enter button interaction and unlimited characters)

### ISSUE THREAD

**Issue by EddyLopez** [FitFast/FitFast-Android#38]
- When creating a password and hitting the green arrow (enter key that should take you to the next available text field), the password text field goes blank for a second and then the password shows back up with the addition of the enter key as a new character in the password.

- Unlimited number of characters can be inserted for a password. (Put a limit on how many characters a password can be).

**Comment by scensorECHO** [comment]
Should be fixed with the same android:single-line="true" field as the other issue

**Comment by ryan-peirce** [comment]
fixed with toms suggestion
