### ISSUE TITLE
EditText increases in size, goes over other Views

### ISSUE THREAD

**Issue by scensorECHO** [FitFast/FitFast-Android#4]
Entering a name and hitting the arrow (enter) key makes the textbox drop down instead of going on to the next text field. If that textbox is extended all the way down over ‘Age’ and ‘Weight’ attempting to click on ‘Age’ or ‘Weight’ results in clicking on the enlarged ‘Name’ textbox.

After typing out ‘51st’ and then hitting the green arrow (enter) key many times, the textbox for ‘Name:’ gets extended below. In the middle of the screen you see a pink line across the ‘150’ value. That is actually the textbox that is a part of ‘51st’. Assuming there was no value under ‘Age:’ and having the ‘51st’ textbox extended, clicking on ‘Age:’ (trying to insert your age) instead will open up ‘51st’ textbox.

Potential Fix: Set android:single-line="true"
in the XML of any textboxes we have. There's no need for any of them to extend past one line.
<a href="http://stackoverflow.com/questions/10978038/restrict-edittext-to-single-line">StackOverflow answer on this topic.</a>

**Comment by ryan-peirce** [comment]
Should all be set to single line now
