### ISSUE TITLE
Weight limit uncapped

### ISSUE THREAD

**Issue by EddyLopez** [FitFast/FitFast-Android#40]
- An unrealistic weight can be input. Put a maximum limit on it? Be it character length, or an actual value.

This doesn't seem to have any sort of affect (Layout issues) on the DashBoard, but I would imagine it will affect the fitness library calculations.

**Comment by scensorECHO** [comment]
We could limit by length, but the record weight is 1400 pounds which makes a String length of 3 a limit that does not work for any person. We could parse the value then test it, like:

if(Double.parseDouble(weightField.getText().toString())<1500) { // logic }
