### ISSUE TITLE
Desired # of Weekly Workouts not capped

### ISSUE THREAD

**Issue by EddyLopez** [FitFast/FitFast-Android#41]
- The hint indicates that the user must input 1-7, however 0 and any number above 8 can be input.

A large number does not seem to affect the DashBoard, but I would imagine it will affect the fitness library calculations/ calorie algorithms.

**Comment by scensorECHO** [comment]
if(String.equals("^[1-7])){ // logic } 

Tests first value in string. Also might want to verify String.length() == 1

**Comment by ryan-peirce** [comment]
Done
