### ISSUE TITLE
Values not saved in STATS page

### ISSUE THREAD

**Issue by EddyLopez** [FitFast/FitFast-Android#42]
- After creating an account and visiting the Stats page, the 'Pass' field shows a '0'.

- The Gender, Desired # of Weekly Workouts, Activity Level, and Time Frame values are not saved.

**Comment by scensorECHO** [comment]
The password should not be shown in general. 

The other values should be properly implemented using SharedPreferences. I'm hoping Ryan will take care of this to get used to the Android standard

**Comment by ryan-peirce** [comment]
Fixed.
