### ISSUE TITLE
Accepts numbers in Name EditText field

### ISSUE THREAD

**Issue by scensorECHO** [FitFast/FitFast-Android#5]
A number can be inserted as your name. I have entered ‘51st’

Potential Fix: <a href="http://stackoverflow.com/questions/10627137/how-can-i-know-when-a-edittext-lost-focus">RegEx the string</a> for alphabetical characters "/^[A-Za-z]+$/" after/during user input

**Comment by EddyLopez** [comment]
This bug still exists. Also documented under Oct25 Data Validation in Google Drive.

**Comment by ryan-peirce** [comment]
Name doubles as a username for us, so this isn't really an issue in my opinion. Plus who are we to say some one cant be named 51st? i mean white people name their kids Sunshine Stardust these days. NFL players rename themselves after their numbers too lol.
