### ISSUE TITLE
Gender settings in stats not linked to DashBoard

### ISSUE THREAD

**Issue by scensorECHO** [FitFast/FitFast-Android#6]
The female button being checked off. Then (after hitting update and being sent to the DashBoard) shows the Gender Is not updated. It stays as Male. 

Currently no logic in the Stats.java activity for processing this. 

Potential Fix: Look at my other comment about implementing SharedPreferences to manage gender, a simple boolean value mapped to "Gender" would suffice, unless we want to be politically correct and allow "Other", link here: [http://techblogon.com/android-sharedpreferences-example-code/]

**Comment by ryan-peirce** [comment]
Fixed, and no "other" for us. If your trans-sexual, fine, but just pick which one you are currently. So, Wes (being born a female) would just pick male. Reason being that, if we use gender in our calculations, we would need to add "other" to those calculations.

**Comment by Wesley2927** [comment]
Lol much appreciated
