### ISSUE TITLE
Height textbox has no indication of units

### ISSUE THREAD

**Issue by scensorECHO** [FitFast/FitFast-Android#8]
Height textbox does not include the feet (‘) and inches (“) symbols. If we don’t want to go that route, it should specify to input your height in inches.

Potential Fix: Specify US standard, flat number in inches or feet and inches and parse input, testing for ft/in input or flat inches.

Reference <a href="https://gist.github.com/scensorECHO/2b9a3c82aaf38fe20a4c">my gist</a> for an example solution.

**Comment by ryan-peirce** [comment]
added units to displays
